#!/bin/bash

SLACK_DIR=/Applications/Slack.app/Contents/Resources/app.asar.unpacked/src/static
u=`tput smul`
nu=`tput rmul`
b=`tput bold`
n=`tput sgr0`

echo -e "\n\t${u}Slack Custom Controls${nu}\n"
echo -e "    Backed up current Slack configuration..."
echo -e "    (to uninstall custom controls run"
echo -e "     uninstall script in this repository)\n"

cp -v $SLACK_DIR/ssb-interop.js ./backup/

echo -e "\n    Installing Controls...\n"

rm $SLACK_DIR/ssb-interop.js
cp -v ./lib/ssb-interop.js $SLACK_DIR/

echo -e "\n    ${b}Complete.${n} Close and Restart Slack Application."
echo -e "    Note: Custom controls waits about 7 seconds from application startup to load...\n"
