#!/bin/bash

SLACK_DIR=/Applications/Slack.app/Contents/Resources/app.asar.unpacked/src/static
u=`tput smul`
nu=`tput rmul`
b=`tput bold`
n=`tput sgr0`

echo -e "\n\t${u}Slack Custom Controls${nu}\n"
echo -e "  Backing up current Slack configuration..."
echo -e "  (To uninstall custom controls run uninstall script in this repository)\n"

cp $SLACK_DIR/ssb-interop.js ./backup/

echo -e "  Installing Controls...\n"

rm $SLACK_DIR/ssb-interop.js
cp ./lib/ssb-interop.js ./lib/dark.css $SLACK_DIR/

echo -e "  ${b}Complete.${n} Close and Restart Slack Application.\n"
