#!/bin/bash

SLACK_DIR=/Applications/Slack.app/Contents/Resources/app.asar.unpacked/src/static
u=`tput smul`
nu=`tput rmul`
b=`tput bold`
n=`tput sgr0`

echo -e "\n\t${u}Slack Custom Controls${nu}\n"

git pull origin master >/dev/null

# Uses root permissions because some users do not own their /Applications directory and therefore cannot perform file operations within Slack.app content directories
echo -e "  - Upgrading...\n"
./uninstall >/dev/null
./install >/dev/null

echo -e "  ${b}Complete.${n} Close and Restart Slack Application.\n"
echo -e "  * Shortcuts *"
echo -e "  ${b}Toggle Dark Mode Theme:${n} ⌘+D"
echo -e "  ${b}Toggle Channels Sidebar:${n} ⌘+B"
